name: teddy g
favicon: null
layout_spectrum: 0.7489656677935272
typography_spectrum: 0.860041047912091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5576211225707084
  lightness: 0.5786629875656217
  saturation: 0.9924411934334785
  rhythmicContrast: 0.8647108967415988
purpose: []
