name: teddy g
favicon: null
layout_spectrum: 0.42314113723114133
typography_spectrum: 0.9222134817391634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6739691020920873
  lightness: 0.6278756093233824
  saturation: 0.231804012786597
  rhythmicContrast: 0.7882148635108024
purpose: []
