name: teddy g
favicon: null
layout_spectrum: 0.99768
typography_spectrum: 0.0737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffe5'
    - '#68685c'
    - '#b4b5a7'
    - '#e7855c'
  brandStrength: 0.6739691020920873
  lightness: 0.6278756093233824
  saturation: 0.231804012786597
  rhythmicContrast: 0.7882148635108024
purpose: []
